# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3073e681500ee76f2b4274e012a29f4c5ca9a3a5e79566e74ff15953ec18052b5721a4d4a2c5c400028552513faf133d408e9ab20adf5c3e8f864283243f1a79

test:
  secret_key_base: 7a2aedd19bdb88d9166bbb42984e136f4d0023764a7e2587ebb6bb588554d79d4059ff43ea2a8f72862d323998bfa4e54a5a855214f8e6b4dc92b39e6bedd844

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
